# E2E Tests (browser only)

default:
    @just --list

# Install dependencies
install:
    pnpm install

# Run e2e tests
test:
    pnpm test

# Run e2e tests in UI mode
test-ui:
    pnpm test:ui

# Check code style and linting
check:
    pnpm check

# Fix code style and linting issues
check-write:
    pnpm check:write
