---
version: 2
updates:
  - package-ecosystem: uv
    directory: '/'
    schedule:
      interval: weekly
    target-branch: 'main'
    groups:
      all-uv:
        patterns:
          - "*"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    target-branch: 'main'
    groups:
      all-gha:
        patterns:
          - "*"
