includes:
  - path: ./src/modai/default_config.yaml

modules:
  auth_oidc:
    collision_strategy: drop
  session:
    class: modai.modules.session.dev_mock_session.DevMockSessionModule
    collision_strategy: replace
    config:
      user_id: "dev-user"
      email: "dev@example.com"
      name: "Dev User"
  openapi_tool_registry:
    config:
      tool_servers:
        - url: http://localhost:8001/openapi.json
