includes:
  - path: ./src/modai/default_config.yaml

modules:
  # Deactivate authentication completely for development purposes.
  auth_oidc:
    collision_strategy: drop
  session:
    class: modai.modules.session.dev_mock_session.DevMockSessionModule
    collision_strategy: replace
    config:
      user_id: "dev-user"
      email: "dev@example.com"
      name: "Dev User"
