includes:
  - path: ./src/modai/default_config.yaml

modules:
  # Deactivate authentication completely for development purposes.
  auth_oidc: !drop
  session: !override
    class: modai.modules.session.dev_mock_session.DevMockSessionModule
    config:
      user_id: "dev-user"
      email: "dev@example.com"
      name: "Dev User"
