orphan: true

repos:
  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        language: system
        entry: pnpm check
        always_run: true
        pass_filenames: false
