name: Tests

on:
  push:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Sync dependencies
        working-directory: backend
        run: uv sync
      - name: Run tests
        working-directory: backend
        run: uv run pytest

  frontend-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: frontend_omni
        run: pnpm install
      - name: Run unit tests
        working-directory: frontend_omni
        run: pnpm test:unit

  frontend-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: frontend_omni
        run: pnpm install
      - name: Install Playwright browsers
        working-directory: frontend_omni
        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        working-directory: frontend_omni
        run: pnpm test:e2e
